homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret vistasea_latitude
  longitude: !secret vistasea_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 15
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Currency:
  currency: USD
  # Customization file
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  allowlist_external_dirs:
    - /config


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

#
# Discover some devices automatically
discovery:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
http:
  ssl_certificate:    !secret ssl_certificate
  ssl_key:            !secret ssl_key

#netgear_lte:
#  - host: !secret lte_modem_host
#    password: !secret lte_modem_pass
#    #scan_interval: 60
#    sensor:
#      monitored_conditions:
#      - usage
#      - connection_text
#      - radio_quality
#      - rx_level
#      - tx_level
#      - current_band

influxdb:
  api_version: 2
  ssl: false
  host: 192.168.32.61
  port: 8086
  token: raven_tworoads_token
  organization: tworoads.net
  bucket: homeassistant_core

telegram_bot:
#  - platform: broadcast
  - platform: polling
    api_key: !secret telegram_apikey
    parse_mode: html # otherwise '_' are interpreted as for italics in msg parser
    allowed_chat_ids:
      - !secret telegram_chatid
      - !secret telegram_userid

notify:
  - name: telegram_vistasea
    platform: telegram
    api_key: !secret telegram_apikey
    chat_id: !secret telegram_chatid #first chat Group "HA Vistasea"
    
camera:
  - platform: local_file
    name: Front Yard Snapshot
    file_path: /config/www/snapshots/vs_front_yard.png
  - platform: local_file
    name: Back Yard Snapshot
    file_path: /config/www/snapshots/vs_back_yard.png

device_tracker:
  - platform: mqtt_json
    devices:
      srp_iphone_ios: 'location/phone/srp_iphone_ios'
      audi_a6_gps: 'location/car/audi_a6_gps'
      audi_q7_gps: 'location/car/audi_q7_gps'
      toyota_rav4_gps: 'location/car/toyota_rav4_gps'

logger:
  default: info
  logs:
    homeassistant.components.command_line.switch: warning
    homeassistant.components.automation: warning
    #homeassistant.components.venstar: debug
    #homeassistant.config: debug
    # homeassistant.components.telegram_bot: debug
    # aiounifi: debug
    # homeassistant.components.unifi: debug

#climate:
#  - platform: venstar
#   host: !secret venstar_main_host
#   ssl: false
#   humidifier: false

envisalink:
  host: !secret envisalink_host
  panel_type: HONEYWELL
  user_name: user
  password: user
  code: '3071'
  port: 4025
  evl_version: 4
  keepalive_interval: 60
  zonedump_interval: 20
  timeout: 10
  zones:
    10:
      name: 'Front Door'
      type: 'door'
    11:
      name: 'Back Door'
      type: 'door'
    12:
      name: 'Upper Deck Door'
      type: 'door'
    13:
      name: 'Bedroom Door'
      type: 'door'
    14:
      name: 'Garage Door'
      type: 'door'
    20:
      name: 'Laundry Room Smoke'
      type: 'smoke'
    21:
      name: 'Lower Hall Smoke'
      type: 'smoke'
    22:
      name: 'Upper Hall Smoke'
      type: 'smoke'
    23:
      name: 'Garage Smoke'
      type: 'smoke'
    27:
      name: 'Lower Motion'
      type: 'motion'
    28:
      name: 'Upper Motion'
      type: 'motion'
    29:
      name: 'Garage Motion'
      type: 'motion'
  partitions:
    1:
      name: 'House Alarm'
    2:
      name: 'Garage Alarm'

input_boolean:
  guest_mode:
    name: Guest Mode

input_number:
  gas_level:
    name: Gas Level
    min: 0
    max: 100
    step: 1
    mode: box

mqtt:
  sensor:
    - state_topic: room-assistant/status/livingroom
      unique_id: room_assistant_livingroom
      name: "Room Assistant Livingroom"
    - state_topic: room-assistant/status/loft
      unique_id: room_assistant_loft
      name: "Room Assistant Loft"
    - state_topic: room-assistant/status/master
      unique_id: room_assistant_master
      name: "Room Assistant Master"
    - state_topic: room-assistant/status/garage
      unique_id: room_assistant_garage
      name: "Room Assistant Garage"
    - state_topic: environment/vistasea_garage/BME280_temperature
      unique_id: garage_temperature
      name: 'Garage Temperature'                                                   
      unit_of_measurement: '..F'                                                   
    - state_topic: 'environment/vistasea_garage/BME280_humidity'                   
      unique_id: garage_humidity
      name: 'Garage Humidity'
    - state_topic: 'environment/vistasea_garage/BME280_pressure'                   
      unique_id: garage_pressure
      name: 'Garage Pressure'                                                      
      unit_of_measurement: 'hPa'                                                   
    - state_topic: 'environment/vistasea_garage/BME280_sealevel_pressure'          
      unique_id: garage_sealevel_pressure
      name: 'Garage Sealevel Pressure'                                             
      unit_of_measurement: 'hPa'                                                   
    - state_topic: 'environment/vistasea_master/BME280_temperature'                
      unique_id: master_temperature
      name: 'Master Temperature'                                                   
      unit_of_measurement: '..F'                                                   
    - state_topic: 'environment/vistasea_master/BME280_humidity'                   
      unique_id: master_humidity
      name: 'Master Humidity'                                            
    - state_topic: 'environment/vistasea_master/BME280_pressure'         
      unique_id: master_pressure
      name: 'Master Pressure'                                            
      unit_of_measurement: 'hPa'                                         
    - state_topic: 'environment/vistasea_master/BME280_sealevel_pressure'
      unique_id: master_sealevel_pressure
      name: 'Master Sealevel Pressure'                                   
      unit_of_measurement: 'hPa'                                         


# Sensors
sensor:
  - platform: helium
    hotspots:
      - 112YavLSSEvDt1HpmABL5rPGRhNXD3ki2gttukjpbLqhjWBgHtiG
  - platform: gpsd
    name: Vistasea GPS
    host: 192.168.32.157
    scan_interval: 60
#  - platform: mqtt
#    name: bme280 Garage
#    state_topic: "environment/vistasea_garage/SENSOR"
#    value_template: "{{ value_json['BME280'].Temperature }}"
#    json_attributes_topic: "environment/vistasea_garage/SENSOR"
#    availability_topic: "environment/vistasea_garage/LWT"
#    payload_available: "Online"
#    payload_not_available: "Offline"
#    unit_of_measurement: 'F'
  # Weewx Weather
  - platform: rest
    resource: http://192.168.32.157/weewx/daily.json
    name: Weewx Weather
    scan_interval: 150
    force_update: true
    json_attributes:
      - time
      - current
      - almanac
    value_template: '{{ value_json.location }}'
  - platform: rest
    name: "Vera House Mode"
    resource: !secret vera_resource
    method: "GET"
    scan_interval: 15
    value_template: >-
      {% set mapper =  {
        '1' : 'Home',
        '2' : 'Away',
        '3' : 'Night',
        '4' : 'Vacation' } %}
      {{ mapper[value] }}
  - platform: rest
    name: "Massive Chambray Buffalo LED"
    unique_id: massive_chambray_buffalo_led
    scan_interval: 300 # 5 min
    resource: !secret bobcat_led
    value_template: "{{value_json.led}}"
  # Local System monitor
  - platform: systemmonitor
    resources:
      - type: memory_use_percent
      - type: swap_use_percent
      - type: disk_use_percent
        arg: /
      - type: processor_use
      - type: load_1m
      - type: last_boot
      - type: processor_temperature
#  - platform: noaa_tides
#    station_id: 9446489
# Time and date
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
#      - 'date_time'
#      - 'date_time_utc'
#      - 'date_time_iso'
#      - 'time_date'
#      - 'time_utc'
  - platform: snmp
    host: 192.168.32.162
    baseoid: 1.3.6.1.2.1.25.1.8.1
    name: raspi_livingroom_vs_cpu_temperature
    scan_interval: 60
    accept_errors: true
    value_template: "{{ value }}"
    unit_of_measurement: " °C"
  - platform: snmp
    host: 192.168.32.163
    baseoid: 1.3.6.1.2.1.25.1.8.1
    name: raspi_garage_vs_cpu_temperature
    scan_interval: 60
    accept_errors: true
    value_template: "{{ value }}"
    unit_of_measurement: " °C"
  - platform: snmp
    host: 192.168.30.1
    baseoid: 1.3.6.1.4.1.88888.1.1.16.1.1.2.101.1
    name: Mofi4500 LTE Band
    version: 2c
    scan_interval: 23
    accept_errors: true
    value_template: "{{ value }}"
  - platform: snmp
    host: 192.168.30.1
    version: 2c
    name: Mofi4500 LTE RSRQ
    unit_of_measurement: 'dB'
    baseoid: 1.3.6.1.4.1.88888.1.1.16.1.1.4.101.1
    accept_errors: true
    scan_interval: 27
    value_template: '{{value | float}}'
  - platform: snmp
    host: 192.168.30.1
    version: 2c
    name: Mofi4500 LTE RSRP
    unit_of_measurement: 'dB'
    baseoid: 1.3.6.1.4.1.88888.1.1.16.1.1.5.101.1
    accept_errors: true
    scan_interval: 27
    value_template: '{{value | float}}'
  - platform: snmp
#    host: 192.168.30.1
    host: 192.168.32.254
    version: 2c
    name: Mofi4500 LTE Usage
    scan_interval: 23
    unit_of_measurement: 'MiB'
#    baseoid: 1.3.6.1.4.1.88888.1.1.16.1.1.7.101.1
    baseoid: 1.3.6.1.4.1.8072.1.3.2.4.1.2.10.119.97.110.95.117.115.97.103.101.0.1 
    accept_errors: true
    value_template: '{{value | float(default=0)}}'
  - platform: snmp
    name: erx_wan_in
    host: 192.168.32.254
    baseoid: 1.3.6.1.2.1.31.1.1.1.6.4
    community: public
    version: '2c'
    scan_interval: 10
    accept_errors: true
  - platform: snmp
    name: erx_wan_out
    host: 192.168.32.254
    baseoid: 1.3.6.1.2.1.31.1.1.1.10.4
    community: public
    version: '2c'
    scan_interval: 10
    accept_errors: true
  - platform: derivative
    name: erx_wan_in_derivative
    source: sensor.erx_wan_in
    unit_time: s
    unit: B
  - platform: derivative
    name: erx_wan_out_derivative
    source: sensor.erx_wan_out
    unit_time: s
    unit: B
#  - platform: statistics
#    name: erx_wan_in_statistics
#    entity_id: sensor.erx_wan_in
#    sampling_size: 86400
#    max_age: 24:00:00
#  - platform: statistics
#    name: erx_wan_out
#    entity_id: sensor.erx_wan_out
#    sampling_size: 86400
#    max_age: 24:00:00
  - platform: statistics
    name: mofi4500_lte_statistics
    entity_id: sensor.mofi4500_lte_usage
    state_characteristic: change
    sampling_size: 28800
    max_age:
      hours: 24
  - platform: history_stats
    name: Heat Pump Duty Cycle
    entity_id: binary_sensor.heat_pump_status
    state: "on"
    type: ratio
    #start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
    duration:
      hours: 24
  - platform: history_stats
    name: Heat Pump Time On
    entity_id: binary_sensor.heat_pump_status
    state: "on"
    type: time
    #start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
    duration:
      hours: 24
  - platform: history_stats
    name: Heat Pump On Count
    entity_id: binary_sensor.heat_pump_status
    state: "on"                                                   
    type: count
    #start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
    duration:
      hours: 24
  - platform: integration                 
    source: sensor.ups_current_power                                      
    name: UPS Current Energy
    unit_prefix: k              
    unit_time: h                                                                                
    round: 2                      

switch:
  - platform: command_line
    switches:
      vistasea_pi_hole:
        command_on: !secret vistasea_pihole_enable 
        command_off: !secret vistasea_pihole_disable
        command_state: !secret vistasea_pihole_status
        value_template: "{{ value_json.status == 'enabled' }}"

utility_meter:                                                                   
  daily_energy:                            
    source: sensor.house_total_energy
    cycle: daily                         
  monthly_energy:    
    source: sensor.house_total_energy
    cycle: monthly         

input_select:
  home_status:
    name: Home Status
    options:
      - Home
      - Arrived
      - Left
      - Away
      - Night
      - Guest
      - Vacation
    initial: Home

# NWS weather
#weather:
#  - platform: nws
#    mode: hourly # default daynight
#    api_key: srp@tworoads.net
weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily
    scan_interval:
      minutes: 15

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/bignumber-card/bignumber-card.js
      type: module
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/secondaryinfo-entity-row/secondaryinfo-entity-row.js
      type: module
    - url: /hacsfiles/flex-horseshoe-card/flex-horseshoe-card.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/home-assistant-sun-card/home-assistant-sun-card.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/compass-card/compass-card.js                   
      type: module
    - url: /hacsfiles/battery-state-card/battery-state-card.js
      type: module

frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

history: !include history.yaml
recorder: !include recorder.yaml
group: !include groups.yaml
zone: !include zones.yaml
#binary_sensor: !include binary_sensors.yaml
automation: !include automations.yaml
automation split: !include_dir_list automations
template: !include templates.yaml
rest_command: !include rest.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
