binary_sensor:                                                           
  - name: 'Both Home'                                                                   
    unique_id: both_home            
    state: "{{ is_state('person.scott', 'home') and is_state('person.stephanie', 'home') }}"                                                                            
  - name: 'Both Away'                                                                
    unique_id: both_away                                                             
    state: "{{ not is_state('person.scott', 'home') and not is_state('person.stephanie', 'home') }}"                                                   
  - name: 'Motion Home'
    unique_id: motion_home
    state: >
      {%- set counter = namespace(total=0) %}
      {%- for sensor in expand('group.motion_sensors') %}
        {%- if now() - as_datetime(sensor.attributes.last_tripped_time) < timedelta(seconds=600) %}
          {%- set counter.total = counter.total + 1 %}
        {%- endif %}
      {%- endfor %}
      {{ iif(counter.total > 0, true, false) }}
  - name: 'Heat Pump Status'
    unique_id: heat_pump_status
    state: >-
      {%- set action = state_attr('climate.main_floor', 'hvac_action') %}
      {{ action == "heating" or action == "cooling" }}
sensor:
  - name: 'House Power Demand'
    unique_id: house_power_demand
    icon: mdi:transmission-tower
    device_class: power
    unit_of_measurement: 'kW'                                                                   
    state: "{{ ((states('sensor.house_total_power')) | float(default=0) / 1000) | round(2) }}"    
  - name: 'Internet In Mbps'
    unique_id: internet_in_mbps
    unit_of_measurement: 'Mbps'
    icon: mdi:download-network
    state: "{{ [((states('sensor.erx_wan_in_derivative') | float(default=0) * 8) / 1000000) | round(2), 0] | max }}"
  - name: 'Internet Out Mbps'
    unique_id: internet_out_mbps
    icon: mdi:upload-network
    unit_of_measurement: 'Mbps'
    state: "{{ [((states('sensor.erx_wan_out_derivative') | float(default=0) * 8) / 1000000) | round(2), 0] | max }}"
  - name: "UPS Battery Minutes"                                           
    state: "{{ states('sensor.ups_battery_runtime') | multiply(0.0167) | float(default=0) | round(0) }}"
    unit_of_measurement: "min"                                                       
  - name: "UPS Current Power"                                                                                                                   
    state: "{{ (states('sensor.ups_load') | float(default=0)) * (states('sensor.ups_nominal_real_power') | float(default=0) ) / 100.0 }}"
    device_class: power                                                                   
    unit_of_measurement: "W"                                                                                                
  - name: 'Downstairs Thermostat Temperature'                                             
    unique_id: downstairs_thermostat_temperature                                                                                    
    state: "{{ state_attr('climate.downstairs', 'current_temperature') }}"                
    unit_of_measurement: "..F"                                                           
  - name: 'Processor Temperature C'
    unique_id: processor_temperature_c
    state: "{{ ((states('sensor.processor_temperature') | float(default=0)) - 32) | multiply(0.5556) |  round(1) }}"
    unit_of_measurement: '°C'
  - name: 2G Wifi Count                                                                                                                                              
    unique_id: 2g_wifi_count
    state: "{{ states.device_tracker | selectattr('state', 'eq', 'home') | selectattr('attributes.radio_proto', 'defined') | selectattr('attributes.radio_proto', 'eq', 'ng') | list | count }}"                 
  - name: 5G Wifi Count                                                                                                                                              
    unique_id: 5g_wifi_count                                                                                                                                         
    state: "{{ states.device_tracker | selectattr('state', 'eq', 'home') | selectattr('attributes.radio_proto', 'defined') | selectattr('attributes.radio_proto', 'search', '(ac|na)') | list | count }}"                 
  - name: Guest Wifi Count                                                                                                                                              
    unique_id: guest_wifi_count                                                                                                                                         
    state: "{{ states.device_tracker | selectattr('state', 'eq', 'home') | selectattr('attributes.radio_proto', 'defined') | selectattr('attributes.essid', 'eq', 'guest-vistasea') | list | count }}"                 
  - name: Heat Pump Cycle Length
    unique_id: heat_pump_cycle_length
    unit_of_measurement: 'min'
    state: "{{ ((states('sensor.heat_pump_time_on') | int(default=0) * 60) / (states('sensor.heat_pump_on_count') | int(default=0))) | round(0) }}"
  - name: Audi A6 Distance                                                                                          
    unique_id: audi_a6_distance                                                                                             
    state: "{{ state_attr('sensor.audi_a6_ibeacon_room_presence', 'distance') }}"            
    unit_of_measurement: 'm'                                                                                               
  - name: Audi Q7 Distance                                                           
    unique_id: audi_q7_distance                              
    state: "{{ state_attr('sensor.audi_q7_ibeacon_room_presence', 'distance') }}"
    unit_of_measurement: 'm'
  - name: Toyota Rav4 Distance
    unique_id: toyota_rav4_distance
    state: "{{ state_attr('sensor.toyota_rav4_ibeacon_room_presence', 'distance') }}"
    unit_of_measurement: 'm'             
  - name: "TMHI 5G SINR"
    unique_id: tmhi_5g_sinr
    unit_of_measurement: "dbm"
    icon: mdi:signal
    state: "{{ state_attr('sensor.tmhi_radio_status', 'signal') ['5g'] ['sinr']  }}"
  - name: "TMHI 5G RSRP"
    unique_id: tmhi_5g_rsrp
    unit_of_measurement: "dbm"
    icon: mdi:signal
    state: "{{ state_attr('sensor.tmhi_radio_status', 'signal') ['5g'] ['rsrp']  }}"
  - name: "TMHI 5G RSSI"
    unique_id: tmhi_5g_rssi
    unit_of_measurement: "dbm"
    icon: mdi:signal
    state: "{{ state_attr('sensor.tmhi_radio_status', 'signal') ['5g'] ['rssi']  }}"
  - name: "TMHI 5G Band"
    unique_id: tmhi_5g_band
    icon: mdi:signal-5g
    state: "{{ state_attr('sensor.tmhi_radio_status', 'signal') ['5g'] ['bands'] [0] }}"
  - name: WeeWx Weather Update
    unique_id: weewx_weather_update
    state: "{{ states.sensor.weewx_weather.attributes['time'] }}"
  - name: WeeWx Outside Temperature
    unique_id: weewx_outside_temperature
    unit_of_measurement: '°F'
    state: "{{ states.sensor.weewx_weather.attributes.current['outTemp'] }}"
  - name: WeeWx Outside Dewpoint                                                                       
    unique_id: weewx_outside_dewpoint                                                                                 
    unit_of_measurement: "°F"                                                                             
    state: "{{ states.sensor.weewx_weather.attributes.current['dewpoint'] }}"                        
  - name: WeeWx Outside Windchill
    unique_id: weewx_outside_windchill                                                                                 
    unit_of_measurement: "°F"                                                                              
    state: "{{ states.sensor.weewx_weather.attributes.current['windchill'] }}"                        
  - name: WeeWx Outside Heat Index
    unique_id: weewx_outside_heat_index                                                                                 
    unit_of_measurement: "°F"                                                                              
    state: "{{ states.sensor.weewx_weather.attributes.current['heatindex'] }}"                        
  - name: WeeWx Rain Rate                                            
    unique_id: weewx_rain_rate
    unit_of_measurement: "in/h"   
    state: "{{ states.sensor.weewx_weather.attributes.current['rainRate'] }}"
  - name: WeeWx Rain Day              
    unique_id: weewx_rain_day
    state: "{{ states.sensor.weewx_weather.attributes.current['rainDaySum'] }}"
    unit_of_measurement: "in"
  - name: WeeWx Rain Year   
    unique_id: weewx_rain_year
    unit_of_measurement: "in"
    state: "{{ states.sensor.weewx_weather.attributes.current['rainYearSum'] }}"
  - name: WeeWx Loft Temperature
    unique_id: weewx_loft_temperature
    unit_of_measurement: '°F'
    state: "{{ states.sensor.weewx_weather.attributes.current['inTemp'] }}"
  - name: WeeWx Outside Humidity
    unique_id:  weewx_outside_humidity
    icon: mdi:water-percent 
    unit_of_measurement: '%'
    state: "{{ states.sensor.weewx_weather.attributes.current['outHumidity'] }}"
  - name: WeeWx Loft Humidity
    unique_id: weewx_loft_humidity
    icon: mdi:water-percent 
    unit_of_measurement: '%'
    state: "{{ states.sensor.weewx_weather.attributes.current['inHumidity'] }}"
  - name: WeeWx Wind Speed  
    unique_id: weewx_wind_speed
    icon: mdi:weather-windy 
    unit_of_measurement: 'mph'
    state: "{{ states.sensor.weewx_weather.attributes.current['windSpeed'] }}"
  - name: WeeWx Wind Direction Ordinal
    unique_id: weewx_wind_direction_ordinal
    icon: mdi:weather-windy 
    state: "{{ states.sensor.weewx_weather.attributes.current['windDirText'] }}"
  - name: WeeWx Cloudbase   
    unique_id: weewx_cloudbase                                                             
    unit_of_measurement: "ft"
    state: "{{ states.sensor.weewx_weather.attributes.current['cloudbase'] }}"   
  - name: WeeWx Solar Altitude
    unique_id: weewx_solar_altitude
    unit_of_measurement: '°'
    state: "{{ states.sensor.weewx_weather.attributes.almanac.sun['altitude'] }}"
  - name: 'TMHI 5G Usage GB'
    unit_of_measurement: 'GiB'                                                                                                                                          
    state: "{{ ( states('sensor.tmhi_5g_usage') | float(default=0) / 1024) | round(2) }}"                       
  - name: "Last Boot Date Time"                                                                                     
    unique_id: last_boot_date_time                                                                                                                     
    state: "{{ states.sensor.last_boot.state.split('T')[0] }}"                                                       
  - name: "Current Date/Time"                                                                                        
    unique_id: current_date_time                                                                                     
    state: "{{ now().strftime('%a, %b %e') + now().strftime(' %-I:%M %p') }}"                                                                                      
  - name: Kitchen Freezer Sensor Age
    unique_id: kitchen_freezer_sensor_age
    state: "{{ (states.sensor.time.last_changed - states.sensor.kitchen_freezer_temperature.last_changed).total_seconds() | round(0) }}"
    unit_of_measurement: "Seconds"
  - name: Wine Chiller Sensor Age
    unique_id: wine_chiller_sensor_age
    state: "{{ (states.sensor.time.last_changed - states.sensor.wine_chiller_temperature.last_changed).total_seconds() | round(0) }}"
    unit_of_measurement: "Seconds"
  - name: Garage Chiller Sensor Age
    unique_id: garage_chiller_sensor_age
    state: "{{ (states.sensor.time.last_changed - states.sensor.garage_chiller_temperature.last_changed).total_seconds() | round(0) }}"
    unit_of_measurement: "Seconds"
  - name: Pump Room Sensor Age
    unique_id: pump_room_sensor_age
    state: "{{ (states.sensor.time.last_changed - states.sensor.pump_room_temperature.last_changed).total_seconds() | round(0) }}"
    unit_of_measurement: "Seconds"
  - name: Massive Chambray Buffalo Update
    unique_id: massive_chambray_buffalo_update
    state: "{{ (state_attr('sensor.massive_chambray_buffalo', 'block') | int(default=0)) - (state_attr('sensor.massive_chambray_buffalo', 'last_poc_challenge') | int(default=0)) | int(default=0) }}"
    unit_of_measurement: "blocks"
