# Notify door opening
id: 'notifydooropening'
alias: "N: Door Opening"
initial_state: 'on'
trigger:
  platform: state
  entity_id: >
    binary_sensor.front_door, binary_sensor.back_door,
    binary_sensor.bedroom_door, binary_sensor.upper_deck_door,
    binary_sensor.garage_door
condition:
  condition: and
  conditions:
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ states('sensor.vera_house_mode') != 'Home' }}"
        - condition: template
          value_template: "{{ states('alarm_control_panel.house_alarm') != 'disarmed' }}"
    - condition: template
      value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
action:
  service: !secret telegram_notify
  data_template:
    message: >
      {% if is_state(trigger.entity_id, 'on') %}
        {{ trigger.to_state.name }} is open
      {% else %}
        {{ trigger.to_state.name }} is closed
      {% endif %}

