id: 'vehiclefrontyard'
alias: 'N: Vehicle Front Yard'
mode: single
max_exceeded: silent
trigger:
  platform: state
  entity_id: binary_sensor.vs_front_yard_vehicle_detected
  to: 'on'
action:
#  - service: camera.snapshot
#    data:
#      entitiy_id: camera.vs_front_yard_high
#      filename: "/config/www/snapshots/hv_front_yard.png"
  - service: !secret telegram_notify
    data_template:
      message: "Vehicle passed Front Yard"

