- alias: notify_when_device_unavailable
  initial_state: 'on'
  trigger:
    platform: state
    entity_id:
      - sensor.sp111_01_status
      - sensor.sp111_02_status
      - sensor.sp111_03_status
      - sensor.sp111_04_status
    to: 'unavailable'
  action:
  - service: notify.notify
    data_template:
      message: "{{ trigger.to_state.attributes.friendly_name }} has gone offline"
