# Daily lte usage report
id: 'dailylteusagereport'
alias: 'N: Daily LTE Usage report'
trigger:
  platform: time
  at: '06:00:00'
action:
  service: automation.trigger
  entity_id: automation.lte_usage_report

