substitutions:
  name: esp32-bluetooth-proxy-d09a28
  friendly_name: Bluetooth Proxy d09a28
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: 8Qoaj48febtrVFR1+rucpSTf2Djo3wIBZfRGCeVOfho=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
