esphome:
  name: twelvevolt-sensor1
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "9aa4efa779d51e73028af8d765ae3606"

wifi:
  ssid: "srp-vistasea"
  password: "kicker87"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Twelvevolt-Sensor1"
    password: "BWTiqYpSecJe"

captive_portal:

deep_sleep:
  run_duration: 2min
  sleep_duration: 60min

sensor:
  - platform: adc
    pin: A0
    name: "Battery1 Voltage"
    update_interval: 60s
    filters:
      - multiply: 14.84
      
